# Generated by Django 5.1.6 on 2025-02-21 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('⌛', 'Pending'), ('✔', 'Confirmed'), ('✖', 'Cancelled')], default='⌛', max_length=1),
        ),
    ]
