# Generated by Django 5.1.6 on 2025-02-21 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_alter_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('⌛', '⌛'), ('✔', '✔'), ('✖', '✖')], default='⌛', max_length=1),
        ),
    ]
