# Generated by Django 5.1.6 on 2025-02-26 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_alter_appointment_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={},
        ),
        migrations.AddField(
            model_name='appointment',
            name='video_call_room',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
