# Generated by Django 5.1.6 on 2025-02-20 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='doctor/')),
                ('Specialization', models.CharField(max_length=100)),
                ('Qualification', models.CharField(max_length=100)),
                ('Experience', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('Contact', models.CharField(max_length=10)),
                ('Address', models.TextField()),
            ],
        ),
    ]
