# Generated by Django 5.1.6 on 2025-02-25 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='problems',
            field=models.TextField(blank=True),
        ),
    ]
